@BASE_URL = http://localhost:3000/api

###
GET {{BASE_URL}}/users
###
GET {{BASE_URL}}/books

###
POST {{BASE_URL}}/admins
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin"
}

###
POST {{BASE_URL}}/books
Content-Type: application/json

{
    "kitapadi" : "Kayıp Tanrılar Ülkesi",
    "kitapyazar" : "Ahmet Ümit",
    "kitapyayinevi":  "Yapı Kredi Yayınları",
    "kitapturu" : "kitaptürü3",
    "sayfasayisi" : "23",
    "ciltno": "4"
}

###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "tcno" : "123456789",
    "adsoyad" : "Ahmet Ümit",
    "telefon":  "6665555555",
    "eposta" : "esposta@drive.com",
    "adres" : "Ankara"
    
}

###
PATCH  {{BASE_URL}}/users/123123/Kitap2
Content-Type: application/json

{
    "tcno" : "123456789",
    "adsoyad" : "Ahmet Ümit",
    "telefon":  "6665555555",
    "eposta" : "esposta@drive.com",
    "adres" : "Ankara"
    
}